[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "paddleocr>=3.4.0",
    "paddlepaddle>=3.3.0",
    "psycopg[binary]>=3.2.0",
]
